# Sparse Matrix

In [16]:
import numpy as np
from scipy.sparse import csr_matrix, bsr_matrix, csc_matrix, dia_matrix, coo_matrix

## Compressed Sparse Row Matrix

In [27]:
row_idxs = [0, 0, 1, 2, 3, 3]
col_idxs = [0, 1, 2, 3, 2, 3]
values = [1, 2, 3, 4, 5, 6]

csr_matrix((values, (row_idxs, col_idxs)), shape=(4,4)).toarray()

array([[1, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4],
       [0, 0, 5, 6]])

In [47]:
row_idxs = [0, 0, 1, 2, 3, 3]
col_idxs = [0, 1, 2, 3, 3, 3]
values = [1, 1, 1, 1, 1, 1]

csr_matrix((values, (row_idxs, col_idxs)), shape=(4,4)).toarray()

array([[1, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 2]])

## Block Sparse Row Matrix

In [28]:
row_idxs = [0, 0, 1, 2, 3, 3]
col_idxs = [0, 1, 2, 3, 2, 3]
values = [1, 2, 3, 4, 5, 6]

bsr_matrix((values, (row_idxs, col_idxs)), shape=(4,4)).toarray()

array([[1, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4],
       [0, 0, 5, 6]])

In [44]:
row_idxs = [0, 0, 1, 2, 3, 3]
col_idxs = [0, 1, 2, 3, 3, 3]
values = [1, 1, 1, 1, 1, 1]

bsr_matrix((values, (row_idxs, col_idxs)), shape=(4,4)).toarray()

array([[1, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 2]])

## 	COOrdinate Matrix

In [43]:
row_idxs = [0, 0, 1, 2, 3, 3]
col_idxs = [0, 1, 2, 3, 3, 3]
values = [1, 1, 1, 1, 1, 1]

coo_matrix((values, (row_idxs, col_idxs)), shape=(4,4)).toarray()

array([[1, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 2]])

## Diagonal Matrix

In [31]:
offset = 0 ## kind of diagonal location
values = [1, 2, 3, 4, 5, 6]

dia_matrix((values, offset), shape=(4,4)).toarray()

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [32]:
offset = 1
values = [1, 2, 3, 4, 5, 6]

dia_matrix((values, offset), shape=(4,4)).toarray()

array([[0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4],
       [0, 0, 0, 0]])

In [37]:
offset = [0, -1, 2]
values = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [3, 5, 8, 2]
])

dia_matrix((values, offset), shape=(4,4)).toarray()

array([[1, 0, 8, 0],
       [5, 2, 0, 2],
       [0, 6, 3, 0],
       [0, 0, 7, 4]])