In [1]:
from scipy import stats 
import numpy as np 


In [2]:
a = np.array([86, 47, 45, 47, 40, 97, 98, 75, 65, 83])

In [3]:
## mean
a.mean()

68.3

In [4]:
## median
np.median(a)

70.0

In [5]:
## variance 
## average of squared difference of each datapoint from dataset's mean
a.var()

454.21000000000004

In [6]:
## standard deviation 
## sqrt of variance 
a.std()

21.312203077110542

In [7]:
## std and var 
## for sample of data not entire population
a.var(ddof=1) , a.std(ddof=1)

(504.6777777777778, 22.46503455990615)

In [8]:
## mode
stats.mode(a)

ModeResult(mode=array([47]), count=array([2]))

In [9]:
## range (max - min)
np.ptp(a)

58

In [10]:
## percentile 
## a value ,below which lies given the percentage of data points 
np.percentile(a,100,interpolation='lower')

98

In [11]:
## Quartiles 
np.percentile(a,[25,50,75],interpolation='lower')

array([47, 65, 83])

In [12]:
## Inter Quartile Range (IQR) 
## difference between third quartile Q3 and first quartile Q1

stats.iqr(a,rng=(25,75),interpolation="lower")

36

#### skewness
- majority of the data present on side of the distribution 


| type1 | type2 | type3 |
| ----- | ----- | ----- |
| right skewed | left skewed | unskewed |
| positive value | negative value | zero |

In [13]:
## skewed 
stats.skew(a)

0.04321019390325423

#### Kurtosis
- indicates how much of data is concentrated around mean or shape of the probability distribution.
- default Ficsher definition 
- can be changed to pearson 


In [14]:
## kurtosis
stats.kurtosis(a)

-1.5694354898634155

## Random Sampling 

- Select Items randomly from population, either with or without replacement.
- Random choice 

In [18]:
## 2 items are selected randomly 

np.random.choice([12,11,56,23],2,replace=False)

array([12, 11])

## Random Seeding 

- To get random choice generated but has to be generated everytime has to be same for peer checking or to generate same results. Get same randomly generated sequence everytime if seed value is determined.
- <b>SEED</b> is a value sets initial state of random number generator.


In [38]:
## It will generate same random number everytime 
np.random.seed(100)
np.random.rand()

0.5434049417909654

## Random Variable

- A set of all possible outcomes of a random experiment is called <b>SAMPLE SPACE</b>
- probability of all outcomes : Probability Distribution
- Random Variable maps to one of the outcomes of the sample space

## Probability Distributions 

        Discrete Probability Distribution 
                    |
                    v
        Probability Mass Function
                    |
                    v
        Continuous form
                    |
                    v
        Probability Density Function 


| Distribution Type | Examples |
| ----------------- | ----------- |
| Discrete Distribution | Binomial, Poisson, Hypergeometric, Multinomial, Negative Binomial |
| Continuous Distribution | Normal, Uniform, Chi-Sqaure, F, T |


## Random Distributions
scipy.stats module provide a lot of methods for created discrete and continuous random variables.

Commonly used methods are described below.

- pdf / pmf : Probability distribution function (continuous) or probability mass function (discrete).
- cdf : Cumulative distribution function.
- sf : Survival function (1 – cdf).
- rvs : Creating random samples from a distribution.

- The following example defines a normal continuous random variable of mean 1.0 and std 2.5.
- It also estimates probabilities and cumulative probabilities at -1, 0 and 1.
- The example also generates six random numbers from defined normal distribution.

In [40]:
x = stats.norm(loc=1.0, scale=2.5)

print(x.pdf([-1, 0, 1]))

print(x.cdf([-1, 0, 1]))

print(x.rvs((2,3)))

[0.11587662 0.14730806 0.15957691]
[0.2118554  0.34457826 0.5       ]
[[ 3.33951992  1.44894578 -0.44290376]
 [-0.33343178  0.4364947   0.21270166]]
